In [41]:
################### Importing values ###################

import numpy as np

index_input = np.loadtxt("input_index_7_2.txt", skiprows = 1, dtype = int)

print(index_input)


coordinates_input = np.loadtxt("input_coordinates_7_2.txt", skiprows = 1, dtype = int)

print(coordinates_input)

################### Setting Grid ###################

## Works for example

import numpy as np

l1 = 4
l2 = 8
l3 = 5
l4 = 9
l5 = 6
l6 = 7

grid_test_1 = np.arange(l2 * l1 * l3 * l4 * l5 * l6).reshape(l6, l5, l4, l3, l2, l1)

print(grid_test_1)

# ################### Converting index to coordinates ###################

# x1 is column, x2 is row, x3 is 3D, x4 is 4D

# Creates array for values input later
coordinates_output = np.zeros((np.size(index_input, 0), 6), dtype = int)
# print(coordinates_output)

for i in range(len(index_input)):
    
    # x6 is the rounded down value after dividing with (l1 * l2 * l3 * l4 * l5)
    x6 = index_input[i] // (l1 * l2 * l3 * l4 * l5)
    remainder = index_input[i] % (l1 * l2 * l3 * l4 * l5)
#     print(remainder)
#     print(x6)

    if remainder != 0:
        x5 = remainder // (l1 * l2 * l3 * l4)
        remainder = remainder % (l1 * l2 * l3 * l4)
#         print(remainder)
#         print(x5)
    else:
        x5 = 0
#         print(x5)


    if remainder != 0:
        x4 = remainder // (l1 * l2 * l3)
        remainder = remainder % (l1 * l2 * l3)
#         print(remainder)
#         print(x4)
    else:
        x4 = 0
#         print(x4)  

    if remainder != 0:
        x3 = remainder // (l1 * l2)
        remainder = remainder % (l1 * l2)
#         print(remainder)
#         print(x3)
    else:
        x3 = 0
#         print(x3)

    # x1 is the remainder after dividing with the number of columns
    if remainder != 0:
        x1 = remainder % l1
#         print(remainder)
#         print(x1)
    else:
        x1 = 0
#         print(x1)
    
    # x1 is the remainder after dividing with the number of columns
    if remainder != 0:
        x2 = remainder // l1
#         print(remainder)
#         print(x2)
    else:
        x2 = 0
#         print(x2)
        
    coordinates_output[i] = [x1, x2, x3, x4, x5, x6]
#     print(coordinates_output)

print(index_input)
print(coordinates_output)

export_c = np.savetxt("output_coordinates_7_2.txt", coordinates_output, fmt = '%i', header = "x1, x2, x3, x4, x5, x6", comments = '')

# ################### Converting coordinates to index ###################

# # x1 is column, x2 is row, x3 is 3d

# Creates array for values input later
index_output = np.zeros((np.size(coordinates_input, 0), 1), dtype = int)
# print(coordinates_output)

for i in range(len(coordinates_input)):
    result_index = coordinates_input[i][0] + (coordinates_input[i][1] * l1) + (coordinates_input[i][2] * (l1 * l2))+ (coordinates_input[i][3] * (l1 * l2 * l3)) + (coordinates_input[i][4] * (l1 * l2 * l3 * l4)) + (coordinates_input[i][5] * (l1 * l2 * l3 * l4 * l5))
#     print(result_index)
    index_output[i] = result_index

print(index_output)

export_1 = np.savetxt("output_index_7_2.txt", index_output, fmt = '%i', header = "index", comments = '')

[42985 34130 17187 ... 21014 54924   838]
[[3 2 2 7 4 6]
 [0 0 0 0 2 5]
 [0 2 1 4 5 6]
 ...
 [3 3 3 7 1 4]
 [1 7 3 8 5 2]
 [0 0 1 5 4 4]]
[[[[[[    0     1     2     3]
     [    4     5     6     7]
     [    8     9    10    11]
     ...
     [   20    21    22    23]
     [   24    25    26    27]
     [   28    29    30    31]]

    [[   32    33    34    35]
     [   36    37    38    39]
     [   40    41    42    43]
     ...
     [   52    53    54    55]
     [   56    57    58    59]
     [   60    61    62    63]]

    [[   64    65    66    67]
     [   68    69    70    71]
     [   72    73    74    75]
     ...
     [   84    85    86    87]
     [   88    89    90    91]
     [   92    93    94    95]]

    [[   96    97    98    99]
     [  100   101   102   103]
     [  104   105   106   107]
     ...
     [  116   117   118   119]
     [  120   121   122   123]
     [  124   125   126   127]]

    [[  128   129   130   131]
     [  132   133   134   135]
     [  136 

[42985 34130 17187 ... 21014 54924   838]
[[1 2 3 7 5 4]
 [2 4 1 6 5 3]
 [3 0 2 8 5 1]
 ...
 [2 5 1 5 2 2]
 [0 3 1 1 2 6]
 [2 1 1 5 0 0]]
[[58795]
 [46080]
 [59720]
 ...
 [37231]
 [25885]
 [41152]]


In [27]:
## 3D - Works for example

import numpy as np

l1 = 4
l2 = 3
l3 = 2

grid_test_1 = np.arange(l2 * l1 * l3).reshape(l3, l2, l1)

# print(grid_test_1)

index_value = np.array([[16],
                        [6],
                        [8],
                        [23]])

coord_value = np.array([[2, 0, 1],
                        [3, 1, 0],
                        [1, 1, 0],
                        [2, 2, 0]])


################### Converting index to coordinates ###################

# x1 is column, x2 is row, x3 is 3D

# Creates array for values input later
coordinates_output = np.zeros((np.size(index_value, 0), 3), dtype = int)
# print(coordinates_output)

for i in range(len(index_value)):
    
    # x3 is the remainder after dividing with the number of columns
    x3 = index_value[i] // (l1 * l2)
    remainder = index_value[i] % (l1 * l2)

    # x1 is the remainder after dividing with the number of columns
    if remainder != 0:
        x1 = remainder % l1
#         print(x1)
    else:
        x1 = 0
#         print(x1)
    
    # x1 is the remainder after dividing with the number of columns
    if remainder != 0:
        x2 = remainder // l1
#         print(x2)
    else:
        x2 = 0
#         print(x2)

    coordinates_output[i] = [x1, x2, x3]
#     print(coordinates_output)
    
print(coordinates_output)

################### Converting coordinates to index ###################

# x1 is column, x2 is row, x3 is 3d

# Creates array for values input later
index_output = np.zeros((np.size(coord_value, 0), 1), dtype = int)
# print(coordinates_output)

for i in range(len(coord_value)):
    result_index = coord_value[i][0] + (coord_value[i][1] * l1) + (coord_value[i][2] * (l1 * l2))
#     print(result_index)
    index_output[i] = result_index

print(index_output)

[[0 1 1]
 [2 1 0]
 [0 2 0]
 [3 2 1]]
[[14]
 [ 7]
 [ 5]
 [10]]
